"""remove_assistant_id_from_context_stores

Revision ID: 17fd01a1c9dd
Revises: d853408411c8
Create Date: 2025-11-14 11:57:27.821268

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '17fd01a1c9dd'
down_revision = 'd853408411c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_context_stores_assistant_id'), table_name='context_stores')
    op.drop_constraint('context_stores_assistant_id_fkey', 'context_stores', type_='foreignkey')
    op.drop_column('context_stores', 'assistant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('context_stores', sa.Column('assistant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('context_stores_assistant_id_fkey', 'context_stores', 'assistants', ['assistant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_context_stores_assistant_id'), 'context_stores', ['assistant_id'], unique=False)
    # ### end Alembic commands ###