"""add_assistant_schemas_and_tag_system

Revision ID: 5715f36f819d
Revises: 6ec75a03c792
Create Date: 2025-11-10 15:14:12.468290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5715f36f819d'
down_revision = '6ec75a03c792'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_definitions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value_type', sa.Enum('FREE_TEXT', 'MULTIPLE_CHOICE', 'BOOLEAN', 'NUMBER', name='valuetype'), nullable=False),
    sa.Column('allowed_values', sa.JSON(), nullable=True),
    sa.Column('applies_to', sa.JSON(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_definitions_name'), 'tag_definitions', ['name'], unique=True)
    op.create_table('tag_instances',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tag_definition_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('resource_type', sa.Enum('DOCUMENT', 'EMAIL', name='resourcetype'), nullable=False),
    sa.Column('resource_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tag_definition_id'], ['tag_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_definition_id', 'resource_type', 'resource_id', name='uix_tag_resource')
    )
    op.create_index(op.f('ix_tag_instances_key'), 'tag_instances', ['key'], unique=False)
    op.create_index(op.f('ix_tag_instances_resource_id'), 'tag_instances', ['resource_id'], unique=False)
    op.create_index(op.f('ix_tag_instances_resource_type'), 'tag_instances', ['resource_type'], unique=False)
    op.create_index(op.f('ix_tag_instances_tag_definition_id'), 'tag_instances', ['tag_definition_id'], unique=False)
    op.create_table('tagger_rules',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope_type', sa.Enum('FOLDER', 'INBOX', name='scopetype'), nullable=False),
    sa.Column('folder_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('inbox_id', sa.Integer(), nullable=True),
    sa.Column('tag_definition_ids', sa.JSON(), nullable=False),
    sa.Column('assistant_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auto_trigger', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistants.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.ForeignKeyConstraint(['inbox_id'], ['email_inboxes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tagger_rules_assistant_id'), 'tagger_rules', ['assistant_id'], unique=False)
    op.create_index(op.f('ix_tagger_rules_folder_id'), 'tagger_rules', ['folder_id'], unique=False)
    op.create_index(op.f('ix_tagger_rules_inbox_id'), 'tagger_rules', ['inbox_id'], unique=False)
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.add_column('assistants', sa.Column('provider', sa.String(length=50), nullable=True))
    op.add_column('assistants', sa.Column('model', sa.String(length=100), nullable=True))
    op.add_column('assistants', sa.Column('temperature', sa.Float(), server_default='0.7', nullable=False))
    op.add_column('assistants', sa.Column('input_schema', sa.JSON(), server_default='{}', nullable=False))
    op.add_column('assistants', sa.Column('output_schema', sa.JSON(), server_default='{}', nullable=False))
    op.add_column('assistants', sa.Column('initial_messages', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistants', 'initial_messages')
    op.drop_column('assistants', 'output_schema')
    op.drop_column('assistants', 'input_schema')
    op.drop_column('assistants', 'temperature')
    op.drop_column('assistants', 'model')
    op.drop_column('assistants', 'provider')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.drop_index(op.f('ix_tagger_rules_inbox_id'), table_name='tagger_rules')
    op.drop_index(op.f('ix_tagger_rules_folder_id'), table_name='tagger_rules')
    op.drop_index(op.f('ix_tagger_rules_assistant_id'), table_name='tagger_rules')
    op.drop_table('tagger_rules')
    op.drop_index(op.f('ix_tag_instances_tag_definition_id'), table_name='tag_instances')
    op.drop_index(op.f('ix_tag_instances_resource_type'), table_name='tag_instances')
    op.drop_index(op.f('ix_tag_instances_resource_id'), table_name='tag_instances')
    op.drop_index(op.f('ix_tag_instances_key'), table_name='tag_instances')
    op.drop_table('tag_instances')
    op.drop_index(op.f('ix_tag_definitions_name'), table_name='tag_definitions')
    op.drop_table('tag_definitions')
    # ### end Alembic commands ###