"""Add default_model to LLMProvider

Revision ID: 65d620ff04e6
Revises: a5ef80ff439d
Create Date: 2025-11-13 16:48:23.614184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '65d620ff04e6'
down_revision = 'a5ef80ff439d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_providers', sa.Column('default_model', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_providers', 'default_model')
    # ### end Alembic commands ###