"""add_document_folder_tables

Revision ID: 6ec75a03c792
Revises: e71758903317
Create Date: 2025-11-10 13:41:09.257097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ec75a03c792'
down_revision = 'e71758903317'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###