"""change email inbox ids to uuid

Revision ID: 77a4ae1faf22
Revises: 5715f36f819d
Create Date: 2025-11-11 16:07:56.567716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77a4ae1faf22'
down_revision = '5715f36f819d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')

    # Drop foreign key constraints first
    op.execute("ALTER TABLE email_inbox_rules DROP CONSTRAINT IF EXISTS email_inbox_rules_inbox_id_fkey")
    op.execute("ALTER TABLE tagger_rules DROP CONSTRAINT IF EXISTS tagger_rules_inbox_id_fkey")
    op.execute("ALTER TABLE emails DROP CONSTRAINT IF EXISTS emails_inbox_id_fkey")

    # Convert email_inboxes.id to UUID
    op.execute("ALTER TABLE email_inboxes ALTER COLUMN id DROP DEFAULT")
    op.execute("DROP SEQUENCE IF EXISTS email_inboxes_id_seq CASCADE")
    op.execute("ALTER TABLE email_inboxes ALTER COLUMN id TYPE UUID USING gen_random_uuid()")
    op.execute("ALTER TABLE email_inboxes ALTER COLUMN id SET DEFAULT gen_random_uuid()")

    # Convert email_inbox_rules.id and inbox_id to UUID
    op.execute("ALTER TABLE email_inbox_rules ALTER COLUMN id DROP DEFAULT")
    op.execute("DROP SEQUENCE IF EXISTS email_inbox_rules_id_seq CASCADE")
    op.execute("ALTER TABLE email_inbox_rules ALTER COLUMN id TYPE UUID USING gen_random_uuid()")
    op.execute("ALTER TABLE email_inbox_rules ALTER COLUMN id SET DEFAULT gen_random_uuid()")
    op.execute("ALTER TABLE email_inbox_rules ALTER COLUMN inbox_id TYPE UUID USING gen_random_uuid()")

    # Convert tagger_rules.inbox_id to UUID (nullable)
    op.execute("ALTER TABLE tagger_rules ALTER COLUMN inbox_id TYPE UUID USING CASE WHEN inbox_id IS NULL THEN NULL ELSE gen_random_uuid() END")

    # Convert emails.inbox_id to UUID (nullable)
    op.execute("ALTER TABLE emails ALTER COLUMN inbox_id TYPE UUID USING CASE WHEN inbox_id IS NULL THEN NULL ELSE gen_random_uuid() END")

    # Recreate foreign key constraints
    op.execute("ALTER TABLE email_inbox_rules ADD CONSTRAINT email_inbox_rules_inbox_id_fkey FOREIGN KEY (inbox_id) REFERENCES email_inboxes(id)")
    op.execute("ALTER TABLE tagger_rules ADD CONSTRAINT tagger_rules_inbox_id_fkey FOREIGN KEY (inbox_id) REFERENCES email_inboxes(id)")
    op.execute("ALTER TABLE emails ADD CONSTRAINT emails_inbox_id_fkey FOREIGN KEY (inbox_id) REFERENCES email_inboxes(id)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tagger_rules', 'inbox_id',
               existing_type=postgresql.UUID(as_uuid=True),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('email_inboxes', 'id',
               existing_type=postgresql.UUID(as_uuid=True),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('email_inboxes_id_seq'::regclass)"))
    op.alter_column('email_inbox_rules', 'inbox_id',
               existing_type=postgresql.UUID(as_uuid=True),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('email_inbox_rules', 'id',
               existing_type=postgresql.UUID(as_uuid=True),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###