"""Update Assistant to use LLMProvider FK

Revision ID: a5ef80ff439d
Revises: 720bcad8c6b7
Create Date: 2025-11-13 15:55:39.178724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a5ef80ff439d'
down_revision = '720bcad8c6b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('llm_provider_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_assistants_llm_provider_id'), 'assistants', ['llm_provider_id'], unique=False)
    op.create_foreign_key(None, 'assistants', 'llm_providers', ['llm_provider_id'], ['id'])
    op.drop_column('assistants', 'provider')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'assistants', type_='foreignkey')
    op.drop_index(op.f('ix_assistants_llm_provider_id'), table_name='assistants')
    op.drop_column('assistants', 'llm_provider_id')
    # ### end Alembic commands ###