"""add_is_system_to_properties

Revision ID: d853408411c8
Revises: 65d620ff04e6
Create Date: 2025-11-14 10:31:04.759591

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd853408411c8'
down_revision = '65d620ff04e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('is_system', sa.Boolean(), nullable=False, server_default='false'))
    op.alter_column('properties', 'is_system', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'is_system')
    # ### end Alembic commands ###